[package]
name = "netzip_parser"
version = "0.1.0"
edition = "2024"
description = "A barebones low-level ZIP parser"
categories = ["parser-implementations"]
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror = "2.0.12"
scroll = "0.13.0"
